#### (1) 그룹화와 집계

In [1]:
import pandas as pd 
# 데이터 로드 
file_path = "../datasets/heart.csv" 
df = pd.read_csv(file_path)

# 컬럼명 변경 
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', 
							'최대심박수', '운동유발협심증', 'ST우울증', '운동후ST경사', '주요혈관수', 
							'결함유형', '심장질환여부']

# 데이터 확인 
print("변경된 데이터프레임 컬럼명:") 
print(df.columns) 
print("\n데이터 상위 5개 행:") 
print(df.head())

# 성별을 기준으로 데이터 그룹화 
grouped = df.groupby('성별')

# 그룹별 데이터 확인 
print("그룹화된 데이터 (성별 기준):") 
grouped.size() # 각 그룹의 행 개수 출력

변경된 데이터프레임 컬럼명:
Index(['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', '최대심박수', '운동유발협심증',
       'ST우울증', '운동후ST경사', '주요혈관수', '결함유형', '심장질환여부'],
      dtype='str')

데이터 상위 5개 행:
   나이  성별  흉통유형  안정시혈압  콜레스테롤  공복혈당  심전도  최대심박수  운동유발협심증  ST우울증  운동후ST경사  \
0  63   1     3    145    233     1    0    150        0    2.3        0
1  37   1     2    130    250     0    1    187        0    3.5        0
2  41   0     1    130    204     0    0    172        0    1.4        2
3  56   1     1    120    236     0    1    178        0    0.8        2
4  57   0     0    120    354     0    1    163        1    0.6        2

   주요혈관수  결함유형  심장질환여부
0      0     1       1
1      0     2       1
2      0     2       1
3      0     2       1
4      0     2       1
그룹화된 데이터 (성별 기준):

성별
0     96
1    207
dtype: int64

#### (2) 피벗테이블 조작

In [2]:
import pandas as pd 
# 데이터 로드 
file_path = "../datasets/heart.csv" 
df = pd.read_csv(file_path)

# 컬럼명 변경 
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', 
              '최대심박수', '운동유발협심증', 'ST우울증', '운동후ST경사', '주요혈관수', 
              '결함유형', '심장질환여부']

# 피벗테이블 생성 
pivot = df.pivot_table(
    index='성별',   # 행
    columns='흉통유형',   # 열
    values='최대심박수', aggfunc='mean')  # 값

# 결과 출력 
print("성별과 흉통유형별 평균 최대심박수:") 
pivot

성별과 흉통유형별 평균 최대심박수:

흉통유형           0           1           2           3
성별
0     145.282051  162.833333  151.800000  149.500000
1     138.759615  162.187500  158.173077  157.315789

#### (3) 인덱스와 컬럼 계층 변경

In [3]:
import pandas as pd 
# 데이터 로드 
file_path = "../datasets/heart.csv" 
df = pd.read_csv(file_path)

# 컬럼명 변경 
df.columns = ['나이', '성별', '흉통유형', '안정시혈압', '콜레스테롤', '공복혈당', '심전도', 
              '최대심박수', '운동유발협심증', 'ST우울증', '운동후ST경사', '주요혈관수', 
              '결함유형', '심장질환여부']

# 피벗테이블 생성 
pivot = df.pivot_table(index='성별', columns='흉통유형', values='최대심박수', aggfunc='mean')

# 데이터 확인 
print("데이터프레임 상위 5개 행:") 
print(df.head())

데이터프레임 상위 5개 행:
   나이  성별  흉통유형  안정시혈압  콜레스테롤  공복혈당  심전도  최대심박수  운동유발협심증  ST우울증  운동후ST경사  \
0  63   1     3    145    233     1    0    150        0    2.3        0
1  37   1     2    130    250     0    1    187        0    3.5        0
2  41   0     1    130    204     0    0    172        0    1.4        2
3  56   1     1    120    236     0    1    178        0    0.8        2
4  57   0     0    120    354     0    1    163        1    0.6        2

   주요혈관수  결함유형  심장질환여부
0      0     1       1
1      0     2       1
2      0     2       1
3      0     2       1
4      0     2       1

In [4]:
# 성별과 흉통유형을 기준으로 그룹화하여 평균 계산 
grouped = df.groupby(['성별', '흉통유형']).mean()

# 그룹화된 데이터 확인 
print("\n성별과 흉통유형 기준 다중 인덱스:") 
grouped

성별과 흉통유형 기준 다중 인덱스:

                나이       안정시혈압       콜레스테롤      공복혈당       심전도       최대심박수  \
성별 흉통유형
0  0     57.256410  138.589744  267.538462  0.128205  0.538462  145.282051
   1     51.944444  128.055556  251.444444  0.111111  0.555556  162.833333
   2     54.971429  127.885714  261.057143  0.114286  0.600000  151.800000
   3     63.250000  147.500000  247.000000  0.250000  0.750000  149.500000
1  0     55.105769  129.557692  243.605769  0.125000  0.451923  138.759615
   1     51.031250  128.593750  241.031250  0.093750  0.656250  162.187500
   2     52.538462  132.057692  231.134615  0.250000  0.596154  158.173077
   3     54.315789  139.473684  235.052632  0.210526  0.315789  157.315789

          운동유발협심증     ST우울증   운동후ST경사     주요혈관수      결함유형    심장질환여부
성별 흉통유형
0  0     0.461538  1.356410  1.179487  0.820513  2.282051  0.461538
   1     0.111111  0.461111  1.666667  0.555556  2.000000  0.888889
   2     0.057143  0.474286  1.571429  0.257143  2.028571  0.971429
   3     0.000000  1.575000  1.500000  0.500000  2.000000  1.000000
1  0     0.596154  1.393269  1.288462  1.019231  2.509615  0.201923
   1     0.062500  0.234375  1.687500  0.343750  2.218750  0.781250
   2     0.173077  1.015385  1.461538  0.807692  2.326923  0.673077
   3     0.210526  1.352632  1.210526  0.473684  2.315789  0.631579

In [5]:
# 다중 인덱스 초기화 
grouped_reset = grouped.reset_index()

print("\n다중 인덱스 초기화:") 
grouped_reset

다중 인덱스 초기화:

,성별,흉통유형,나이,안정시혈압,콜레스테롤,공복혈당,심전도,최대심박수,운동유발협심증,ST우울증,운동후ST경사,주요혈관수,결함유형,심장질환여부
0,0,0,57.256410,138.589744,267.538462,0.128205,0.538462,145.282051,0.461538,1.356410,1.179487,0.820513,2.282051,0.461538
1,0,1,51.944444,128.055556,251.444444,0.111111,0.555556,162.833333,0.111111,0.461111,1.666667,0.555556,2.000000,0.888889
2,0,2,54.971429,127.885714,261.057143,0.114286,0.600000,151.800000,0.057143,0.474286,1.571429,0.257143,2.028571,0.971429
3,0,3,63.250000,147.500000,247.000000,0.250000,0.750000,149.500000,0.000000,1.575000,1.500000,0.500000,2.000000,1.000000
4,1,0,55.105769,129.557692,243.605769,0.125000,0.451923,138.759615,0.596154,1.393269,1.288462,1.019231,2.509615,0.201923
5,1,1,51.031250,128.593750,241.031250,0.093750,0.656250,162.187500,0.062500,0.234375,1.687500,0.343750,2.218750,0.781250
6,1,2,52.538462,132.057692,231.134615,0.250000,0.596154,158.173077,0.173077,1.015385,1.461538,0.807692,2.326923,0.673077
7,1,3,54.315789,139.473684,235.052632,0.210526,0.315789,157.315789,0.210526,1.352632,1.210526,0.473684,2.315789,0.631579

In [6]:
# 다중 컬럼 피벗테이블 생성 
pivot = df.pivot_table(index='성별', columns=['흉통유형', '운동후ST경사'], values='최대심박수', aggfunc ='mean')

print("\n다중 컬럼 피벗테이블:") 
pivot

다중 컬럼 피벗테이블:

흉통유형          0                              1                           2  \
운동후ST경사       0           1           2      0           1       2       0
성별
0        146.00  139.000000  161.400000    NaN  160.500000  164.00  160.00
1        126.75  128.431034  157.052632  168.5  139.833333  167.25  171.25

흉통유형                                 3
운동후ST경사           1           2      0           1           2
성별
0        149.153846  153.047619  114.0         NaN  161.333333
1        147.250000  164.107143  147.5  159.272727  157.000000

In [7]:
# 다중 컬럼 피벗테이블 생성 
pivot = df.pivot_table(index='성별', columns=['흉통유형', '운동후ST경사'], values='최대심박수', aggfunc ='mean')

print("\n다중 컬럼 피벗테이블:") 
pivot

다중 컬럼 피벗테이블:

흉통유형          0                              1                           2  \
운동후ST경사       0           1           2      0           1       2       0
성별
0        146.00  139.000000  161.400000    NaN  160.500000  164.00  160.00
1        126.75  128.431034  157.052632  168.5  139.833333  167.25  171.25

흉통유형                                 3
운동후ST경사           1           2      0           1           2
성별
0        149.153846  153.047619  114.0         NaN  161.333333
1        147.250000  164.107143  147.5  159.272727  157.000000